### ISSUE TITLE
The need for generating serialVersionUID

### ISSUE THREAD

**Issue by TasneemZh** [stalk-calvin/tetris-game#1]
I am new to Java, so I haven't heard of serializable classes before, but I read about them and realized that they are important. The thing is that I believe you didn't declare a serialVersionUID for a reason. I searched the Internet for solving that issue but they (the people on the Internet) can't agree on implementing the default one or generating it. Since you are the creator of this project, I have to know what you suggest

I need this project for running, testing and analyzing
Thanks for this amazing game

**Comment by stalk-calvin** [comment]
Hello, where do you see the serializable in this project?

**Comment by TasneemZh** [comment]
At DrawingBoard and Tetris class

**Comment by stalk-calvin** [comment]
Well, I am not exactly sure what you mean by them being serializable classes.

Anyway, the Tetris game doesn't have to implement any serialization because the game does not require to do any obfustication. Serialization, in general, is useful when exchanging data between 2 machines. Anyways, Serialization should not be taken lightly, rather there are many considerations to take account before implementing it. You can look it up online to understand further the concept. 

There shouldn't and isn't any serialization done in this game.
